export const PROJECTS = [
  {
    id: "rural-digital-health-survey-2026",
    status: "Open",
    field: "Public Health",
    title: "Rural Digital Health Survey 2026",
    description: "A multi-state longitudinal study examining digital health tool adoption in rural primary healthcare centres across Rajasthan, MP and Odisha.",
    pm: { name: "Dr. Kavitha Rao", institution: "PHFI Delhi", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=80&q=80" },
    seats: { total: 30, remaining: 8 },
    deadline: "30 Jul 2026",
    duration: "3 months",
    skills: ["Survey design", "SPSS", "Field research"],
    certificate: true,
    guide: "PDF + Excel templates provided",
  },
  {
    id: "climate-crop-yield-mapping",
    status: "Open",
    field: "Environmental Science",
    title: "Climate Change Impact on Kharif Crop Yields",
    description: "Mapping yield anomalies in wheat and paddy across 120 districts using IMD climate data, MNCFC satellite imagery and historical APEDA datasets.",
    pm: { name: "Rohan Mehta", institution: "IIT Bombay", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&q=80" },
    seats: { total: 25, remaining: 12 },
    deadline: "15 Aug 2026",
    duration: "2 months",
    skills: ["GIS", "Python", "Data analysis"],
    certificate: true,
    guide: "Training data + GIS layers provided",
  },
  {
    id: "social-media-academic-performance",
    status: "Upcoming",
    field: "Psychology & Education",
    title: "Social Media Use & Academic Performance in Undergraduates",
    description: "Cross-sectional study across 5 central universities examining TikTok/Instagram usage patterns and their correlation with CGPA and cognitive load metrics.",
    pm: { name: "Dr. Riya Mehta", institution: "JNU", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&q=80" },
    seats: { total: 20, remaining: 20 },
    deadline: "1 Aug 2026",
    duration: "4 months",
    skills: ["Questionnaire design", "SPSS", "Qualitative analysis"],
    certificate: true,
    guide: "Survey instrument provided",
  },
  {
    id: "biodiversity-index-western-ghats",
    status: "Open",
    field: "Ecology",
    title: "Biodiversity Index Mapping — Western Ghats Corridors",
    description: "Camera-trap and transect data collection across 3 forest divisions in Maharashtra to compute species richness and Shannon diversity indices.",
    pm: { name: "Dr. Arjun Patel", institution: "IISER Pune", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=80&q=80" },
    seats: { total: 15, remaining: 3 },
    deadline: "20 Jul 2026",
    duration: "6 months",
    skills: ["Field ecology", "R", "Camera trap analysis"],
    certificate: true,
    guide: "Field manual + species checklist",
  },
  {
    id: "air-quality-iot-delhi-ncr",
    status: "Completed",
    field: "Environmental Engineering",
    title: "IoT-Based Air Quality Monitoring — Delhi NCR 2025",
    description: "Deployed 40 low-cost IoT PM2.5 sensors across Delhi-NCR over 6 months. Dataset published on Zenodo; 3 papers under review.",
    pm: { name: "Dr. Pooja Verma", institution: "IISc Bangalore", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=80&q=80" },
    seats: { total: 20, remaining: 0 },
    deadline: "Completed Jan 2026",
    duration: "6 months",
    skills: ["IoT", "Python", "Air quality modelling"],
    certificate: true,
    guide: null,
  },
];
